%{
function to store all data file names in a struct for easy access in an 
input deck. Struct field names denote the wind tunnel run's purpose. Struct 
field contents are the appropriate wind tunnel run data file. This function
is meant to streamline wind tunnel data reading in an input deck. 

By John Rangel 11/29/16
%}

function S = data_files()

% data files:
data_file_struct = struct('static_tare', 'stat-1620-0011.txt',...
                            'Qsweep', 'stat-1620-0012.txt',...
                            'alpha_sweep', 'stat-1620-0013.txt',...
                            'alpha_sweep_negative_half_elevator', 'stat-1620-0014.txt',...
                            'beta_sweep', 'stat-1620-0015.txt',...
                            'takeoff_elevator_sweep', 'stat-1620-0016.txt',...
                            'cruise_aileron_sweep', 'stat-1620-0017.txt',...
                            'cruise_elevator_sweep', 'stat-1620-0018.txt',...
                            'cruise_rudder_sweep', 'stat-1620-0019.txt',...
                            'static_tare_with_prop', 'stat-1620-0020.txt',...
                            'takeoff_Emax_elevator', 'stat-1620-0021.txt',...
                            'cruise_Esweep_ElevatorSweep', 'stat-1620-0022.txt', ...
                            'cruise_Esweep_RudderSweep', 'stat-1620-0023.txt');

% pass back file names:
S = data_file_struct;

end % end function